### ISSUE TITLE
Suggestion - Port used by default by diva

### ISSUE THREAD

**Issue by Infer114** [shamirlabs/diva-alpha-net#12]
Diva use port 9000 by default, and it's the same port than lighthouse's listening p2p, and most of other CL clients too.
Maybe that could be better and more friendly to change it for some other one, so it would be possible to have all ports by default on both diva and CL clients.

**Comment by yorickdowne** [comment]
To add to this, host-mapping 9000 (web3signer) feels very much like a dev convenience, same with 30,000. These might just not be host-mapped any longer as the stack matures.

**Comment by yorickdowne** [comment]
Solved by #31
