### ISSUE TITLE
Suggestion - use docker volumes to make data more portable and respect /etc/docker/daemon.json

### ISSUE THREAD

**Issue by actuallymentor** [shamirlabs/diva-alpha-net#19]
Currently the `docker-compose` files use direct file bindings.

Using docker volumes would make the stack respect the path setting in `/etc/docker/daemon.json` and make the management of volumes a bit easier.

This is the approach the RP smartnode stack takes.

**Comment by yorickdowne** [comment]
This can :100: work for consensus DB, execution DB, and diva DB. The way that validator shares its keymanager jwt with reloader right now is better suited to a bind mount, but that's a) a negligible amount of storage and b) if keen, could also be solved without bind mount and using a named volume.

**Comment by yorickdowne** [comment]
So this is now still a bind mount, but configurable as to where. Good enough?

**Comment by actuallymentor** [comment]
@yorickdowne it's good enough for me, but volumes are still a step up over the long term I think

**Comment by yorickdowne** [comment]
I agree. Volumes also make it possible run `diva` as "not root", which is arguably better for security
