### ISSUE TITLE
UI does not distinguish between Pending and Active

### ISSUE THREAD

**Issue by yorickdowne** [shamirlabs/diva-alpha-net#39]
It lies! It lies!!! :grinning: 

For example https://goerli.beaconcha.in/validator/0x833b0019eda36cabf8016c6e7d9bc219020705c5d6309922a1804132534670a7e218d4c5884e6dc8b8c49348c7660344#deposits as of right now is pending but the operator UI claims:

![image](https://github.com/shamirlabs/diva-alpha-net/assets/71337066/93360b82-2e4a-42a5-a195-7580a21b69df)

Active, not so much. Pending, yes.

**Comment by pradavc** [comment]
Fixed in the new operato UI `v23.8.5`. I will close this issue.
