### ISSUE TITLE
Doing Debian/Ubuntu package

### ISSUE THREAD

**Issue by olivierb2** [shamirlabs/diva-alpha-net#46]
I was thinking to make Debian/Ubuntu package to provide alternative way to deploy Diva Operator. Usual way is instead using docker-compose file, we can use systemd service, Debian repository for updates, and proper config files in path like /etc/diva/config.

Does something like this is interresting other people or everybody here prefer to use docker container.

**Comment by pradavc** [comment]
Hi @olivierb2 ,
It sounds very interesting (the more options, the better). We were also debating about just publishing the binary in the next release. 
Are you willing to contribute by building the package? If so, how can we help?
Take into account that the operator UI needs a server anyway, but you can also run it locally.

**Comment by mrabino1** [comment]
While I do use docker and love the simplicity, I do think there is a benefit to reducing the number of sw packages that are requirements to run a node.. and potentially attack vectors.. and dependencies..  many folks (me included) prefer running a service on linux itself not a docker instance.... and while the documentation definitely needs to be expanded, I believe the trade off justifies it..  my 0.02.. thx.

**Comment by pradavc** [comment]
Most of the services are telemetry, which helps us debug the testnet and better understand what is happening. But definitely, we can work on an ubuntu package or provide just the binaries so they can be executed directly as services. In any case, my only concern is not the Diva package but the rest of the services requiring the same approach (vector, prometheus, jaeger, etc). That is a more significant effort than simply providing a package, especially when configuring all of them.

**Comment by mrabino1** [comment]
challenge accepted.. :) joking aside, I do think having the configuration be more broadly used, will also allow for greater flexibility and debugging..

**Comment by olivierb2** [comment]
Can we work together on this? Do you have a channel for communication?

**Comment by franjoespejo** [comment]
closing this as it has been inactive. Please feel free to reopen
