### ISSUE TITLE
Caught SIGNAL in blst_cgo_init

### ISSUE THREAD

**Issue by realsteel85** [shamirlabs/diva-alpha-net#47]
When i run docker logs diva i got this message multiple times.
`Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md`

It's on a Dell R630. 
https://github.com/bnb-chain/bsc/issues/1521 has maybe te solution.

`export CGO_CFLAGS="-O -D__BLST_PORTABLE__" `
`export CGO_CFLAGS_ALLOW="-O -D__BLST_PORTABLE__"`

Can you make a portable version of the installation for older cpu's?
The machine is maybe what older but powerful enough to run Diva :)

**Comment by pradavc** [comment]
@realsteel85, we will test that for the next release. I will make sure to keep you posted.

**Comment by pradavc** [comment]
This will be included in the upcoming release @realsteel85

**Comment by realsteel85** [comment]
@pradavc many thanks 🙏

**Comment by franjoespejo** [comment]
@realsteel85 please feel free to test it 
https://github.com/shamirlabs/diva-alpha-net/commit/e077856aed14ccf801c47eade0b827286f3f86ab

**Comment by franjoespejo** [comment]
Confirmed by https://github.com/EridianAlpha
