### ISSUE TITLE
Operator web interface bugs when the node state is between "registered" and "clients synced"

### ISSUE THREAD

**Issue by franjoespejo** [shamirlabs/diva-alpha-net#57]
In the operator happy path journey there is currently a state with misleading/wrong information:

Once the user is registered, the user lands on the dashboard. If the ethereum clients his node is connected to are in status "connected" but also in "syncing" status:

- The top alerting-header shouldn't say "wrong wallet metamask<->operator", it should say a "still syncing message". Current proposal is: "Your Ethereum node is still syncing, this typically takes a few hours. Your Diva node will become active once your Ethereum node is synced"

- In the settings page, operator address appears as no-operator, current proposal is another "syncing" message  
 
- Clicking the false-alert from the first point above takes the user to a undefined/wrong registration flow. Check the state as could lead us to a unknown bug

**Comment by micho** [comment]
Thanks for filing this @franjoespejo!

**Comment by franjoespejo** [comment]
solved in v24.1.0
