### ISSUE TITLE
Add Teku vc support

### ISSUE THREAD

**Issue by dragonstake** [shamirlabs/diva-alpha-net#59]
We pushed [PR58](https://github.com/shamirlabs/diva-alpha-net/pull/58) that adds Teku validator client support.
The same way we have a separated lodestar compose file I modified the original docker-compose.yml file to add this option.

The fact that the default vc is prysm in diva setup makes it impossible to use your own external lighthouse beacon node. Prysm vc refused to connect to lighthouse. We already have some previous experience using teku vc, so we hope other could leverage this addition.

**Comment by TheHDSync** [comment]
I plan to contribute and add support for Teku once I have some validators assigned, so I can do proper testing.
