### ISSUE TITLE
Bearer Swagger key

### ISSUE THREAD

**Issue by micho** [shamirlabs/diva-alpha-net#65]
I spoke to a user who didn't know the bearer key would later be used for Swagger. Can we make this more clear during the installation process?

**Comment by FUINY7** [comment]
I think it's more peoples that have ZERO knowledge (like me)  and didn't even know what a "bearer"  was and that we should write "bearer" before the API_Key.

**Comment by micho** [comment]
@pradavc im happy to suggest copy for this if you help me understand how it will be used! i was also super confused

**Comment by BitcoinVida** [comment]
Several users have ran into the same issue (including me). Maybe we can include this note (together with others) into a V2.0 of the "Register your node" video.

**Comment by micho** [comment]
I found that the video does indeed show Swagger (see below) and that's confusing

where else does it appear in the first time user experience? @pradavc suggested moving it to an "advanced usage" section

![telegram-cloud-photo-size-4-5935895801417022747-y](https://github.com/shamirlabs/diva-alpha-net/assets/323401/72898b1e-c579-4ac5-90fe-c83de9694365)

**Comment by pradavc** [comment]
I separated the sections into 2 parts, the Swagger section as optional to make it clear. We will introduce changes to the UI as well to make it clear that it is an API for development.

Closing this issue with https://github.com/shamirlabs/docs/pull/35
