### ISSUE TITLE
wipe-dockers.sh is overzealous in cleanup

### ISSUE THREAD

**Issue by heider-andrew** [shamirlabs/diva-alpha-net#66]
Running wipe-dockers.sh (either directly, or via run.sh) is overzealous in cleaning up images. If running RocketPool or other docker based images, they'll inadvertently get picked up in the stop+cleanup.

Suggestion: update wipe-dockers to only target diva images.

**Comment by dohne12** [comment]
Hi @heider-andrew, We will look into it and get back to you soon.
