### ISSUE TITLE
Operator Appears as "Not-Registered" on the Operator UI

### ISSUE THREAD

**Issue by BitcoinVida** [shamirlabs/diva-alpha-net#71]
After completing the node setup, I encountered an issue on the Operator UI, where it displays "Not-Registered."

![Sin título](https://github.com/shamirlabs/diva-alpha-net/assets/55251206/16b45755-37a5-4dc8-a421-61c2f2e5968b)

Upon investigating the problem and consulting responses from the Discord channel #operator-testnet, it appears that this issue occurs because the node still syncs.

**Comment by denchik37** [comment]
A record on the 'Known bugs' page could read:

Delayed node registration

When you submit a node registration request, it may take some time to synchronize, typically up to 24 hours. During this period, your Operator status will temporarily display as "not registered". There's no need to initiate the entire setup process again at this stage.

**Comment by TheHDSync** [comment]
I successfully registered my node and waited more that 24h, but still it shows as not Not-registered.
My EC and BN are fully sync.

**Comment by franjoespejo** [comment]
solved in the last release v24.1.0
