### ISSUE TITLE
Bug - approval display when wrapping divETH

### ISSUE THREAD

**Issue by yorickdowne** [shamirlabs/diva-alpha-net#8]
Shows approval for 32 ETH, should be for 32 divETH

![image](https://github.com/shamirlabs/diva-alpha-net/assets/71337066/2ea3a760-3240-4c06-92a1-bec5ea29f45b)

**Comment by yorickdowne** [comment]
Ditto for wrap display

![image](https://github.com/shamirlabs/diva-alpha-net/assets/71337066/8369710e-6fa3-4703-96b9-74330f15a72c)

**Comment by fernantho** [comment]
Thanks @yorickdowne!
The problem is that the front-end is pointing to an old wdiveth contract. It will be fixed shortly.

**Comment by fernantho** [comment]
Thanks @yorickdowne! This is fixed 
<img width="595" alt="image" src="https://github.com/shamirlabs/diva-alpha-net/assets/19353758/609e35b0-d6e5-4d76-ad7e-8b1892e06566">
